# Generated by Django 2.1.1 on 2018-09-21 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('booking_no', models.CharField(blank=True, max_length=50)),
                ('container_no', models.CharField(blank=True, max_length=50)),
                ('seal_no', models.CharField(blank=True, max_length=50)),
                ('closing_date', models.DateField(blank=True, default=None, max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('work_id', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(choices=[('shipper', 'Shipper'), ('other', 'Other'), ('none', 'None')], default='shipper', max_length=10)),
                ('address_other', models.CharField(blank=True, default='', max_length=500)),
                ('nextday', models.CharField(choices=[('1', 'Yes'), ('0', '-')], default=0, max_length=1)),
                ('cancel', models.CharField(choices=[('1', 'Cancel'), ('0', '-')], default=0, max_length=1)),
            ],
        ),
    ]
